services:
  database:
    image: postgres
    restart: always
    container_name: azimutt-db
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment: # Used by the postgres image to setup a default user. For security reason, you should avoid using the postgres user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yCrfqiUEkpUSgFgr
      POSTGRES_DB: azimutt_dev
  backend:
    container_name: azimutt-backend
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports: # Docker need to expose ports for you to access your app.
      - 3999:3999
    env_file: .env
    environment:
      DATABASE_URL: "ecto://postgres:yCrfqiUEkpUSgFgr@database/azimutt_dev" # Template : "ecto://db_user:db_password@ip_or_compose_service_name/db_name"
      SECRET_KEY_BASE: "V4YJeTqulRvtsjMLx1KVVOG496O3NppQ0mC6SyVCCkUsNMh+OFd+1gPnStXzgk5R" # Can literally be anything, but generally generated randomly by tools like mix phx.gen.secret
volumes:
  pg-data:
